title: SinricPro

tagline: IOT Cloud Platform Documentation

description: >
  Sinric Pro is a IOT Cloud Platform Documentation.

twitter_username: sinricpro
github_username:  sinricpro

url: https://help.sinric.pro

defaults:
  -
    values:
      layout: page
      weight: 100   # Used to sort navbar items. Lower weight goes higher on the list.

markdown: kramdown
highlighter: rouge

google_analytics: G-D9D07HPM4B

environment: production

#exclude: ["pages/pass.md"]

# How to build production
# Change the environment: production / development
# bundle exec jekyll build

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap 